<a href="https://colab.research.google.com/github/nabing259/pandas_practice_set/blob/main/Pandas_Practice_Set_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
# pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [ ]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [ ]:
nd = pd.unique(df['Team'])
# qt = df[df['Team'] == 'Qatar']
# qt = (6/21)*100
dct = {}
for i in nd:
  df2 = df[df['Team'] == i][['Total Attempts', 'On Target']]
  total_attempts = df2['Total Attempts'].sum()
  on_targets = df2['On Target'].sum()
  percent = round((on_targets/total_attempts)*100,2)
  dct[i] = float(str(percent))

sort_dict = dict(sorted(dct.items(), key = lambda item:item[1], reverse=True))
sort_dict

{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.15,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'France': 34.65,
 'Germany': 34.33,
 'Croatia': 33.73,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.33,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [ ]:
df1 = pd.DataFrame(df['Team'].value_counts())
df1['rank'] = df1.rank(method= 'first',ascending = False)
df1

                count  rank
Team
France              7   1.0
Argentina           7   2.0
Croatia             7   3.0
Morocco             7   4.0
Brazil              5   5.0
Portugal            5   6.0
England             5   7.0
Netherlands         5   8.0
Spain               4   9.0
Japan               4  10.0
Switzerland         4  11.0
Korea Republic      4  12.0
Australia           4  13.0
Poland              4  14.0
Senegal             4  15.0
United States       4  16.0
Mexico              3  17.0
Saudi Arabia        3  18.0
Denmark             3  19.0
Tunisia             3  20.0
Iran                3  21.0
Ecuador             3  22.0
Qatar               3  23.0
Wales               3  24.0
Canada              3  25.0
Belgium             3  26.0
Costa Rica          3  27.0
Germany             3  28.0
Uruguay             3  29.0
Cameroon            3  30.0
Ghana               3  31.0
Serbia              3  32.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [ ]:
df.drop(columns=["Sl. No", "Match No.", "Red Cards", "Pts"], inplace=True)
df

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,...,4,15,3,453,387,10,5,1,19,0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,...,2,15,4,484,419,26,10,3,17,1
2,England,Iran,B,6,69,6,0,6,13,7,...,0,9,2,810,733,29,9,8,16,0
3,Iran,England,B,2,20,2,0,1,8,3,...,2,14,2,232,156,11,3,0,10,1
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,...,2,13,2,391,326,22,8,6,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Morocco,Fram,F,0,55,0,0,0,13,1,...,1,11,3,583,518,22,1,3,15,0
124,Croatia,Morocco,F,2,45,2,0,2,14,4,...,0,13,2,491,430,21,3,6,13,0
125,Morocco,Croatia,F,1,45,1,0,0,7,2,...,2,11,2,494,428,20,5,3,15,0
126,Argentina,France,C,3,46,3,0,1,21,9,...,4,26,4,648,544,20,4,6,22,5
127,France,Argentina,D,3,40,3,0,1,10,5,...,3,19,4,516,419,24,3,5,28,4

In [ ]:
df[df.duplicated()].count()

Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
dtype: int64

In [ ]:
df[df.isna()].count()

Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
dtype: int64

In [ ]:
df.describe()

,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,...,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,...,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,...,1.726562,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938
std,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,...,1.514834,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412
min,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000
25%,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,...,1.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000
50%,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,...,2.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000
75%,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,...,2.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000
max,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,...,8.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Team                             128 non-null    object
 1   Against                          128 non-null    object
 2   Group                            128 non-null    object
 3   Goal                             128 non-null    int64
 4   Possession (%)                   128 non-null    int64
 5   Inside Penalty Area              128 non-null    int64
 6   Outside Penalty Area             128 non-null    int64
 7   Assists                          128 non-null    int64
 8   Total Attempts                   128 non-null    int64
 9   On Target                        128 non-null    int64
 10  Off Target                       128 non-null    int64
 11  Target in Penalty                128 non-null    int64
 12  Target from Outside              128 non-null    int64
 13  Left Channel                     128 non-null    int64
 14  Left Inside Channel              128 non-null    int64
 15  Central Channel                  128 non-null    int64
 16  Right Inside Channel             128 non-null    int64
 17  Right Channel                    128 non-null    int64
 18  Receptions MD                    128 non-null    int64
 19  Receptions D                     128 non-null    int64
 20  Attempted Line Breaks            128 non-null    int64
 21  Completed Line Breaks            128 non-null    int64
 22  Attempted Defensive Line Breaks  128 non-null    int64
 23  Completed Defensive Line Breaks  128 non-null    int64
 24  Yellow Cards                     128 non-null    int64
 25  Fouls Against                    128 non-null    int64
 26  Offsides                         128 non-null    int64
 27  Passes                           128 non-null    int64
 28  Passes Completed                 128 non-null    int64
 29  Crosses                          128 non-null    int64
 30  Crosses Completed                128 non-null    int64
 31  Corners                          128 non-null    int64
 32  Free Kicks                       128 non-null    int64
 33  Penalties Scored                 128 non-null    int64
dtypes: int64(31), object(3)
memory usage: 34.1+ KB

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
df['Rank'] = df['Team'].rank(method='first')
df['Rank'] = df['Rank'].astype(np.int16)
df.set_index('Rank', inplace=True)
df.sort_index()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,rank
Rank,,,,,,,,,,,,,,,,,,,,,
1,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,...,7,10,593,525,36,15,9,21,1,4
2,Argentina,Mexico,C,2,50,1,1,2,5,2,...,15,2,533,464,14,2,4,23,0,4
3,Argentina,Poland,C,2,67,1,1,2,25,13,...,11,0,862,814,22,5,9,5,0,4
4,Argentina,Australia,C,2,53,2,0,1,14,5,...,8,4,711,635,6,1,1,15,0,4
5,Argentina,Netherlands,C,2,44,2,0,1,15,6,...,18,2,603,511,16,4,8,30,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Uruguay,Portugal,H,0,35,0,0,0,10,3,...,16,0,390,306,18,5,2,13,0,124
125,Uruguay,Ghana,H,2,39,2,0,1,12,7,...,11,2,446,361,15,4,2,20,0,124
126,Wales,United States,B,1,39,1,0,0,7,3,...,10,1,409,321,15,6,3,15,1,127
127,Wales,Iran,B,0,51,0,0,0,10,3,...,9,2,508,413,20,5,2,12,0,127
128,Wales,England,B,0,33,0,0,0,7,1,...,16,1,325,261,4,1,1,10,0,127

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [ ]:
set1 = pd.read_csv(' https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv')

set1.dropna(subset= 'Age',inplace =True)
set1.shape

(714, 12)

In [ ]:

set2 = pd.read_csv(' https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv')
set2.fillna({'Age':20}, inplace=True)
set2['Age'].isnull().sum()

np.int64(0)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
ipl_matches = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv')
new_name = {
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab' : 'Punjab Kings',
    'Rising Pune Supergiants' : 'Rising Pune Supergiant'
}
ipl_matches.replace(new_name, inplace=True)
ipl_matches.sample(10)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
541,729299,NaN,2014-04-24,2014,11,Royal Challengers Bangalore,Kolkata Knight Riders,Sharjah Cricket Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,2.0,NaN,CA Lynn,"['PA Patel', 'YV Takawale', 'V Kohli', 'Yuvraj...","['JH Kallis', 'G Gambhir', 'MK Pandey', 'CA Ly...",Aleem Dar,VA Kulkarni
379,981007,Kanpur,2016-05-21,2016,54,Gujarat Lions,Mumbai Indians,Green Park,Gujarat Lions,field,N,Gujarat Lions,Wickets,6.0,NaN,SK Raina,"['AJ Finch', 'BB McCullum', 'SK Raina', 'KD Ka...","['RG Sharma', 'MJ Guptill', 'N Rana', 'KH Pand...",AK Chaudhary,CK Nandan
939,335992,Bangalore,2008-04-26,2007/08,12,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,SR Watson,"['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...","['GC Smith', 'M Rawat', 'YK Pathan', 'SR Watso...",MR Benson,IL Howell
473,829745,Bangalore,2015-04-22,2015,20,Royal Challengers Bangalore,Chennai Super Kings,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Chennai Super Kings,Runs,27.0,NaN,SK Raina,"['MS Bisla', 'RR Rossouw', 'V Kohli', 'KD Kart...","['DR Smith', 'BB McCullum', 'SK Raina', 'MS Dh...",JD Cloete,C Shamshuddin
932,335999,Hyderabad,2008-05-01,2007/08,19,Deccan Chargers,Punjab Kings,"Rajiv Gandhi International Stadium, Uppal",Punjab Kings,field,N,Punjab Kings,Wickets,7.0,NaN,SE Marsh,"['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'RG...","['SE Marsh', 'RR Sarwan', 'KC Sangakkara', 'Yu...",BR Doctrove,RB Tiffin
577,598064,Chandigarh,2013-05-06,2013,51,Punjab Kings,Royal Challengers Bangalore,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,field,N,Punjab Kings,Wickets,6.0,NaN,DA Miller,"['Mandeep Singh', 'SE Marsh', 'Gurkeerat Singh...","['CA Pujara', 'CH Gayle', 'V Kohli', 'AB de Vi...",VA Kulkarni,NJ Llong
580,598044,Hyderabad,2013-05-04,2013,48,Sunrisers Hyderabad,Delhi Capitals,"Rajiv Gandhi International Stadium, Uppal",Delhi Capitals,bat,N,Sunrisers Hyderabad,Wickets,6.0,NaN,DJG Sammy,"['PA Patel', 'S Dhawan', 'A Ashish Reddy', 'DJ...","['DPMD Jayawardene', 'V Sehwag', 'UBT Chand', ...",Asad Rauf,S Asnani
227,1178403,Chandigarh,2019-04-13,2019,28,Punjab Kings,Royal Challengers Bangalore,Punjab Cricket Association IS Bindra Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,8.0,NaN,AB de Villiers,"['KL Rahul', 'CH Gayle', 'MA Agarwal', 'SN Kha...","['PA Patel', 'V Kohli', 'AB de Villiers', 'MP ...",S Ravi,UV Gandhe
753,501220,Chandigarh,2011-04-21,2011,23,Punjab Kings,Rajasthan Royals,"Punjab Cricket Association Stadium, Mohali",Rajasthan Royals,field,N,Punjab Kings,Runs,48.0,NaN,SE Marsh,"['AC Gilchrist', 'PC Valthaty', 'SE Marsh', 'K...","['SA Asnodkar', 'R Dravid', 'SR Watson', 'STR ...",S Asnani,PR Reiffel
769,501203,Kolkata,2011-04-11,2011,6,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Kolkata Knight Riders,bat,N,Kolkata Knight Riders,Runs,9.0,NaN,JH Kallis,"['JH Kallis', 'MS Bisla', 'G Gambhir', 'MK Tiw...","['S Dhawan', 'IR Jaggi', 'B Chipli', 'KC Sanga...",RE Koertzen,SK Tarapore

In [ ]:
# ipl_matches[ipl_matches['Team1'] == ipl_matches['WinningTeam']]
team1 = ipl_matches['Team1'].unique()
new_data = pd.DataFrame()
data = []
for i in team1:
  played = ipl_matches[(ipl_matches['Team1'] == i) | (ipl_matches['Team2'] == i)].shape[0]
  win = round((ipl_matches[ipl_matches['WinningTeam'] == i].shape[0]/played)*100,2)
  home = round(ipl_matches[(ipl_matches['Team1'] == i)].shape[0]/played * 100, 2)
  away = round(ipl_matches[(ipl_matches['Team2'] == i)].shape[0]/played * 100, 2)
  data.append([i,played,win, home, away])

new_data[['Team', 'Total Match Played', 'Win%', 'Home Win%', 'Away Win%']] = data
new_data

                           Team Total Match Played   Win% Home Win% Away Win%
0              Rajasthan Royals                192   50.0     46.35     53.65
1   Royal Challengers Bangalore                226  48.23     55.75     44.25
2           Sunrisers Hyderabad                152  49.34     45.39     54.61
3                Delhi Capitals                224  45.98     50.89     49.11
4           Chennai Super Kings                208  58.17     53.37     46.63
5                Gujarat Titans                 16   75.0     43.75     56.25
6          Lucknow Super Giants                 15   60.0     53.33     46.67
7         Kolkata Knight Riders                223  51.12     47.09     52.91
8                  Punjab Kings                218  46.33     50.46     49.54
9                Mumbai Indians                231  56.71     48.48     51.52
10       Rising Pune Supergiant                 30   50.0     46.67     53.33
11                Gujarat Lions                 30  43.33     53.33     46.67
12                Pune Warriors                 46  26.09      50.0      50.0
13              Deccan Chargers                 75  38.67      52.0      48.0
14         Kochi Tuskers Kerala                 14  42.86      50.0      50.0

###`Q-7:` Venues with most "no result" matches.

In [ ]:
ipl_matches[ipl_matches['WonBy'] == "NoResults"]['Venue'].value_counts()

Venue
M Chinnaswamy Stadium    2
M.Chinnaswamy Stadium    1
Feroz Shah Kotla         1
Name: count, dtype: int64

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [94]:
finals = ipl_matches[ipl_matches['MatchNumber'] == 'Final']
team1 = finals['Team1Players']
team2 = finals['Team2Players']

players = []
def get_each(lst):
  return [i.strip("'") for i in lst.lstrip("'[").rstrip("]'").split(', ')]

for i in range(len(team1)):
  t1 = get_each(team1.iloc[i])
  players.extend(t1)
  players.extend(get_each(team2.iloc[i]))

series = pd.Series(players)
series.value_counts().sort_values(ascending=False).head(1)

MS Dhoni    10
Name: count, dtype: int64

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
def season(str):
  df = ipl_matches[ipl_matches['Season'] == str]
  teams = df['Team1'].unique()
  table = []
  points_table = pd.DataFrame()
  for team in teams:
    played = df[(df['Team1'] == team) | (df['Team2'] == team)].shape[0]
    won = df[df['WinningTeam'] == team].shape[0]
    no_result = df[((df['Team1'] == team) | (df['Team2'] == team)) & (df['WinningTeam'].isnull())].shape[0]
    total_points = (won*2)+(no_result*1)
    table.append([team,played, won, no_result, total_points])
  points_table[['TeamName','MatchesPlayed', 'MatchesWon', 'NoResult', 'Points']] = table
  return points_table.sort_values('Points', ascending=False)
season('2022')

                      TeamName MatchesPlayed MatchesWon NoResult Points
5               Gujarat Titans            16         12        0     24
0             Rajasthan Royals            17         10        0     20
1  Royal Challengers Bangalore            16          9        0     18
6         Lucknow Super Giants            15          9        0     18
3               Delhi Capitals            14          7        0     14
8                 Punjab Kings            14          7        0     14
2          Sunrisers Hyderabad            14          6        0     12
7        Kolkata Knight Riders            14          6        0     12
4          Chennai Super Kings            14          4        0      8
9               Mumbai Indians            14          4        0      8

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# def season(str):
#   df = ipl_matches[ipl_matches['Season'] == str]
#   teams = df['Team1'].unique()
#   table = []
#   points_table = pd.DataFrame()
#   for team in teams:
#     played = df[(df['Team1'] == team) | (df['Team2'] == team)].shape[0]
#     won = df[df['WinningTeam'] == team].shape[0]
#     no_result = df[((df['Team1'] == team) | (df['Team2'] == team)) & (df['WinningTeam'].isnull())].shape[0]
#     total_points = (won*2)+(no_result*1)
#     table.append([team,played, won, no_result, total_points])
#   points_table[['TeamName','MatchesPlayed', 'MatchesWon', 'NoResult', 'Points']] = table
#   return points_table.sort_values('Points', ascending=False).head(4)

# year = '2022'
# df = ipl_matches[ipl_matches['Season'] == str]
# pt = season(year)
# pt['SeasonPosition'] =
# pt

,TeamName,MatchesPlayed,MatchesWon,NoResult,Points,SeasonPosition
5,Gujarat Titans,16,12,0,24,1
0,Rajasthan Royals,17,10,0,20,1
1,Royal Challengers Bangalore,16,9,0,18,1
6,Lucknow Super Giants,15,9,0,18,1